approval_policy = "on-failure"
preferred_auth_method = "apikey"
model = "oca/gpt-5-codex"
profile = "gpt-5-codex"
sandbox_mode = "workspace-write"
web_search_request = true
trust_level = "trusted"

[model_providers.oca-responses]
base_url = "https://code-internal.aiservice.us-chicago-1.oci.oraclecloud.com/20250206/app/litellm"
http_headers = { "client" = "codex-cli", "client-version" = "0" }
model = "oca/gpt5"
name = "Oracle Code Assist Responses"
wire_api = "responses"

[model_providers.oca-chat]
base_url = "https://code-internal.aiservice.us-chicago-1.oci.oraclecloud.com/20250206/app/litellm"
http_headers = { "client" = "codex-cli", "client-version" = "0" }
model = "oca/gpt5"
name = "Oracle Code Assist Chat"
wire_api = "responses"

[profiles.grok-4]
model = "oca/grok4"
model_provider = "oca-chat"
review_model = "oca/grok4"

[profiles.grok-4-fast-reasoning]
model = "oca/grok4-fast-reasoning"
model_provider = "oca-chat"
review_model = "oca/grok4-fast-reasoning"

[profiles.grok-code-fast-1]
model = "oca/grok-code-fast-1"
model_provider = "oca-chat"
review_model = "oca/grok-code-fast-1"

[profiles.gpt-4-1]
model = "oca/gpt-4.1"
model_provider = "oca-chat"
review_model = "oca/gpt-4.1"

[profiles.gpt-5]
model = "oca/gpt5"
model_provider = "oca-responses"
review_model = "oca/gpt5"

[profiles.gpt-5-1]
model = "oca/gpt-5.1"
model_provider = "oca-chat"
review_model = "oca/gpt-5.1"

[profiles.gpt-5-2]
model = "oca/gpt-5.2"
model_provider = "oca-responses"
review_model = "oca/gpt-5.2"

[profiles.gpt-5-codex]
model = "oca/gpt-5.3-codex"
model_provider = "oca-responses"
review_model = "oca/gpt-5-codex"
personality = "pragmatic"
model_reasoning_effort = "medium"

[profiles.gpt-5-codex.windows]
sandbox = "elevated"

[profiles.gpt-5-1-codex]
model = "oca/gpt-5.1-codex"
model_provider = "oca-responses"
review_model = "oca/gpt-5.1-codex"
personality = "pragmatic"

[profiles.gpt-5-1-codex-mini]
model = "oca/gpt-5.1-codex-mini"
model_provider = "oca-responses"
review_model = "oca/gpt-5.1-codex-mini"
personality = "pragmatic"

[projects."/home/devindra/code/seaagent1"]
trust_level = "trusted"

[windows]
sandbox = "elevated"

[mcp_servers.mcp-atlassian-jira-sd]
command = "uvx.exe"
args = [
  "--python", "3.12",
  "--from", "mcp-atlassian==0.21.0",
  "--with", "fastmcp==2.14.6",
  "--with", "pydocket==0.17.2",
  "--with", "fakeredis==2.32.1",
  "mcp-atlassian",
  "--transport", "stdio"
]
env = {
  "JIRA_USERNAME" = "YOUR_ORACLE_EMAIL",
  "JIRA_PERSONAL_TOKEN" = "YOUR_JIRA_SD_PAT",
  "JIRA_URL" = "https://jira-sd.mc1.oracleiaas.com",
  "JIRA_SSL_VERIFY" = "false",
  "MCP_VERBOSE" = "true"
}
startup_timeout_sec = 120
enabled = true

[mcp_servers.confluence]
command = "uvx"
args = [
  "--python",
  "3.12",
  "--default-index",
  "https://artifactory.oci.oraclecorp.com/api/pypi/global-dev-pypi/simple",
  "mcp-atlassian",
  "--confluence-url",
  "https://confluence.oraclecorp.com/confluence",
  "--confluence-use-web-session"
]
startup_timeout_sec = 300
